---
title: "Curriculum Vitae"
format: html
---

<div style="margin-bottom: 2rem;">
<a href="assets/cv.pdf" class="btn-primary" download>Download PDF Version</a>
</div>

## Experience

### Policy Analyst (Intern)
**OECD - Trade and Agriculture Directorate (TAD-ARP)**  
*2023–2024*

- Conducted research and analysis on agricultural policies.
- Contributed to reports on resource sustainability and trade trade.

### Research Assistant
**Swedish University of Agricultural Sciences (SLU)**  
*2022–2023*

- Performed data cleaning and statistical analysis for the EU-Horizon project “Contracts2.0”.
- Assisted in preparing datasets for economic modelling.

---

## Education

### PhD in Agricultural Economics
**Wageningen University & Research, Netherlands**  
*2024–Present*

### Double Master's program in Agricultural, Food, and Environmental Policy Analysis (AFEPA) 

* ##### MSc in Business and Economics
    **Swedish University of Agricultural Sciences (SLU), Sweden**

* ##### MSc in Agricultural and Food Economics
    **Universita Cattolica del Sacro Cuore, Italy**  

*2021–2024*  

### BSc in Biotechnology
**University of Verona, Italy**  
*2017–2021*

---

## Certifications

- **Google Data Analyst Professional Certificate** (Coursera, Feb 2023)
- **IELTS English level C1** (British Council, Oct 2021)

---

## Skills

**Programming & Tools**  
STATA, R, Python, SQL, LaTeX, Git

**Languages**  
English (fluent), Italian (fluent), Spanish (basic), French (basic)